In [1]:
#libraries
import pandas as pd
import sys 
from imblearn.over_sampling import SMOTE
import seaborn as sns # used for plot interactive graph. 
import numpy as np # linear algebra
from scipy.stats import randint
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt # this is used for the plot the graph 

In [2]:
testx=pd.read_csv("data files/testx.csv",index_col=0);
testy=pd.read_csv("data files/testy.csv",index_col=0);
trainx=pd.read_csv("data files/trainx.csv",index_col=0);
trainy=pd.read_csv("data files/trainy.csv",index_col=0);

In [4]:
trainx.head()

Temperature (C)  Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0        27.777778                 26.966667      0.31             4.1860   
1        12.072222                 12.072222      0.64            13.6850   
2        17.550000                 17.550000      0.74             7.7763   
3        15.088889                 15.088889      0.93             3.4615   
4        22.233333                 22.233333      0.76             5.7155   

   Wind Bearing (degrees)  Visibility (km)  Pressure (millibars)  precip  
0                   270.0          16.1000               1016.80     1.0  
1                   210.0          16.1000               1016.88     1.0  
2                   171.0           9.9820               1013.55     1.0  
3                    97.0          11.4471               1006.14     1.0  
4                    57.0           6.1019               1014.39     1.0

In [5]:
trainy.head()

summary
0        1
1        1
2        1
3        2
4        1

In [7]:
classifier=GaussianNB();
classifier.fit(trainx,trainy.values.ravel());
prediction=classifier.predict(testx);

In [8]:
print(confusion_matrix(testy,prediction))
print(classification_report(testy,prediction))

[[8360 2684 1528   65  124   14    0   21]
 [5223 3559 2185   66  162   39    1   18]
 [1007 2329 2674   67  465   29    0    7]
 [2144  887  936  296  122    4    0    0]
 [   1   12  144   51 2596    0    0    0]
 [   0    1   20    1    0  143   12   18]
 [   3   16    2    0    0  102   19   65]
 [   6    1    0    1    0   40    8   79]]
              precision    recall  f1-score   support

           1       0.50      0.65      0.57     12796
           2       0.38      0.32      0.34     11253
           3       0.36      0.41      0.38      6578
           4       0.54      0.07      0.12      4389
           5       0.75      0.93      0.83      2804
           6       0.39      0.73      0.51       195
           7       0.47      0.09      0.15       207
           8       0.38      0.59      0.46       135

    accuracy                           0.46     38357
   macro avg       0.47      0.47      0.42     38357
weighted avg       0.46      0.46      0.43     38357

